# Версия docker-compose
version: "3.5"
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx
        # маршрутизируем порты
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_SSL_PORT}:443
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./app/build:/var/app/build
            - ./images/nginx/nginx-server.conf:/etc/nginx/conf.d/nginx-server.conf
            - ./logs/nginx-access.log:/var/log/nginx/access.log
            - ./logs/nginx-error.log:/var/log/nginx/error.log
        # этот образ будет общаться с php и db-mysql
        depends_on:
            - php
            - db-mysql
        # подключим env файл
        env_file:
            - .env

    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php/
        # монтируем директорию с проектами
        volumes:
            - ./app/build:/var/app/build
        # этот образ будет общаться с db-mysql
        depends_on:
            - db-mysql

    db-mysql:
        image: mysql:5.7
        restart: always
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - ${MYSQL_PORT}:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db-mysql:db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always
        ports:
            - ${PHPMYADMIN_PORT}:80
        depends_on:
            - db-mysql
